default: &default
  adapter: postgresql
  username: postgres
  password: welcome

  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_development
  host: localhost
  port: 5432


test:
  <<: *default
  database: admin_test
  host: localhost
  port: 5432




